<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <Deterministic>true</Deterministic>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="dotnet-svcutil.xmlserializer" Version="8.0.0-preview1.24067.4" />
    <PackageReference Include="System.ServiceModel.Http" Version="8.1.2" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="dotnet-svcutil.xmlserializer" Version="8.0.0-preview1.24067.4" />
  </ItemGroup>
</Project>
