@ECHO OFF
PUSHD %~dp0

SET STUB_FILENAME=EamService.cs
SET SRC_STUB_PATH=%~dp0%STUB_FILENAME%
SET DEST_STUB_PATH=%~dp0..\EamService\%STUB_FILENAME%

SET SERDE_FILENAME=EamService.XmlSerializers.cs
SET SRC_SERDE_PATH=%~dp0obj\Release\net8.0\%SERDE_FILENAME%
SET DEST_SERDE_PATH=%~dp0..\EamService\%SERDE_FILENAME%

DEL "%DEST_SERDE_PATH%"
dotnet build -c Release
COPY "%SRC_SERDE_PATH%" "%DEST_SERDE_PATH%"

COPY "%SRC_STUB_PATH%" "%DEST_STUB_PATH%"

POPD
